# -*- coding: utf-8 -*-
"""Escape Character.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sEQxcBHQMrK_q2HkCbo_jC-76lHSsSmQ
"""

print("Dia berkata: 'Pergilah!'")

print ("Aku menimpali: \"Apakah kau ingin aku 'angkat kaki'?!\"")

print (" \\(^_^)/ (\\-_-/)")