# -*- coding: utf-8 -*-
"""Manipulasi String_3 Maula 059.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hQPHpf6DJxD0_mytVUxq8mGsGPa5MwcZ

*   Maula Wulandari
*   2411012059
"""

template = 'Halo, saya %s dari %s'

print(template % ('Maula Wulandari', 'Indonesia'))

template = 'Halo, saya {nama} dari {asal}'
template_2 = 'Saya suka makan {} dan minum {}'

print(template.format(nama = 'Maula Wulandari', asal = 'Indonesia'))
print(template_2.format('dimsum', 'mie ayam', 'matcha'))

nama = 'Maula Wulandari'
asal = 'Indonesia'

print(f'perkenalkan saya {nama} dari {asal}')

alamat = 'Surabaya, Jawa Timur, Indonesia'

print(alamat.split())
print(alamat.split(','))
print(alamat.split(', '))

print('<3'.join(['aku', 'suka', 'python']))
print(':D'.join(alamat.split(', ')))

print('Halo selamat pagi!'.upper())
print('Halo Selamat Siang!'.upper())

print('APA KABAR?'.lower())
print('Lagi Dimana?'.lower())

print('daun tidak pernah membenci angin'.title())
print('LASKAR PELANGI'.title())

print('Indonesia Adalah Negara Kepulauan'.swapcase())
print('aKu cInTa NeGeRiKu'.swapcase())

angka = '12345'

print('Index angka 3:', angka.find('3'))
print('Index angka 45:', angka.find('45'))
print('Index angka 35:', angka.find('35'))

ibu_kota = 'Jakarta'

print(ibu_kota.replace('a', 'i'))
print(ibu_kota.replace('kar', ':D'))
print(ibu_kota.replace('a', ''))

paragraf = 'Baru-baru ini telah ditemukan sebuah meteor di suatu sungai'
x = paragraf.count('di')

print(f'Kata "di" muncul sebanyak {x} kali')