# -*- coding: utf-8 -*-
"""Manipulasi String.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e4j1Y1AqM6jRxA5L6t0T9LWzNBb93n_g

**String**
"""

nama = 'Maula Wulandari'
asal = "Indonesia"

print(nama)

print(asal)

"""**Manipulasi String**"""

print(nama, asal)

print(nama + asal)

print("Halo, nama saya", nama)

print("Halo nama saya", nama, "asal saya dari", asal)

data_lengkap = nama + asal

print(data_lengkap)

"""**String + Non String**"""

asal_kota = "Kebun teletubbies"
kode_pos = 112234

asal_kota_kode_pos = asal_kota + str(kode_pos)

print(asal_kota_kode_pos)

asal_kota_x3 = asal_kota * 3
print(asal_kota_x3)