# -*- coding: utf-8 -*-
"""Operasi String 2 Maula Wulandari 059.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13zw15Eazf_RYHjlm4oC8Tx7jcWKomr-a

**Operasi in Pada String**
"""

berita = 'Ramai-ramai developer di seluruh dunia mulai menggunakan \
  teks editor masa kini seperti Visual Studio Code, \
  atom, sublime text, dan lain sebagainya.'

print('sublime text' in berita)
print('notepad++' in berita)

"""**Memotong String**

**a. Indexing**
"""

nama = 'Strawberry Shortcake'
print(nama[5])
print(nama[7])
print(nama[-1])
print(nama[-3])

"""**b. Slicing String**"""

judul = 'Pelajaran Matematika untuk SD'

print(judul[0:5])
print(judul[:10])
print(judul[10:15])
print(judul[-1:-3])
print(judul[:-3])
print(judul[-5:])

"""**Menghitung Panjang String**"""

print(len('Indonesia'))
print(len('Malaysia'))

"""**Memeriksa Karakter Awal String**"""

nomor_telepon_1 = '081366436713'
nomor_telepon_2 = '623144582394'
nomor_telepon_3 = '+6281270930543'

kode_negara = '+62'
print(nomor_telepon_1.startswith(kode_negara))
print(nomor_telepon_2.startswith(kode_negara))
print(nomor_telepon_3.startswith(kode_negara))

"""**Memeriksa Karakter Akhir String**"""

email_1 = 'dimsum@gmail.com'
email_2 = 'dimsum@outlook.com'

print(email_1.endswith('gmail.com'))
print(email_2.endswith('gmail.com'))