# -*- coding: utf-8 -*-
"""Tipe Data Casting Maula 059.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19DqWs7YmKxKfUVmKAFCdAPVOPadAKA4A

*   Nama: Maula Wulandari
*   NPM: 2411012059
"""

nama = 'Ulaa'
usia = 19
perempuan = True

print(type(nama))
print(type(usia))
print(type(perempuan))

usia = input('Masukkan usia anda')

print(type(usia))

# yang salah

panjang = input('Masukkan panjang: ')
lebar = input('Masukkan lebar: ')

print('Luas =', panjang * lebar)

# yang benar

panjang = int(input('Masukkan panjang: '))
lebar = float(input('Masukkan lebar: '))

print('Luas =', panjang * lebar)

a = 10 / 2
print(type(a))

b = 1 / 2
print(type(b))

kata = 'Strawberry' * 5

print(kata)
print(type(kata))

nama = 'Ulaa'
tahun_lahir = 2006

print(nama + ' lahir di tahun ' + str(tahun_lahir))